name: Release Agent

on:
  workflow_call:

jobs:
  release:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Package Application
        run: |
          mkdir -p publish
          echo "Release Package" > publish/release.txt

      - name: Publish Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-package
          path: publish/